
try:
    number = 32
    print(number)
except:
    print("An error has occurred")

finally:
    print("success")